/*
 * This file was automatically generated by a code gen by Dmidma.
 * It helps get this done quicker.
 * You can delete it and do your thing =D
 */


export const ACTION_TYPE = 'ACTION_TYPE'


export function actionName(data) {
    return {
        type: ACTION_TYPE,
        data
    }
}
